import './globals.css'

export const metadata = {
  title: 'getstrack',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/images/logo.svg' />
      </head>
      <body>{children}</body>
    </html>
  )
}
